# 菜单配置（若不需要某项可直接删除）
menu:
  # 首页
  - id: 首页
    link: /
    icon: home
    class: menu-home
  # 归档
  - id: 归档
    link: /archives
    icon: archive
    class: menu-archive
  # 目录
  - id: 目录
    link: javascript:;
    category: true
    icon: bookmark
    class: menu-category
  # 读书
  - id: 读书
    link: /reading
    icon: book
    class: menu-reading
  # 关于
  - id: 关于
    link: /about
    icon: user
    class: menu-about
  # 搜索
  - id: 搜索
    link: "#search"
    icon: search
    class: menu-search modal-trigger

# 颜色配置
color:
  header: light-blue accent-4
  footer: light-blue accent-4
  page_nav: light-blue accent-4
  side_nav: light-blue accent-4
  tag: pink lighten-1
  article_title_link: blue
  link: pink
  pagination: pink
  tab: pink
  archive_item: grey
  fab: pink
  fab_2: green
  fab_3: yellow darken-1
  new: pink
  about_header: light-blue accent-4
  about_title: light-blue accent-4

excerpt_link: Read More
archive_yearly: true

# 版权信息
copyright: © 2016 example.com, All rights reserved.

# Disqus评论shortname，若为空则不启用
disqus_shortname:
# 多说shortname，若为空则不启用
duoshuo_shortname:

# Google分析track id，若为空则不启用
google_analytics:
# 腾讯分析sId，若为空则不启用
tencent_analytics:

# 高亮的主题，若为空则使用默认主题
google_code_prettify: prettify-tomorrow-night-eighties

# 是否启用MathJax数学公式渲染。如果你确认整个站点的博文都不会用到Latex数学公式，可以将其该项设为false提高页面加载速度
mathjax: true